#!/bin/bash

cd `dirname $0`


start()
{
    echo "start redis server"
    redis-server redis-cluster1.conf
    redis-server redis-cluster2.conf
    redis-server redis-cluster3.conf
}

stop()
{
    echo "stop redis server"
    killall redis-server
}

init()
{
    echo "init cluster"
    for PORT in `seq 7000 7002`
    do
        echo "flushall" | redis-cli -p $PORT
        echo "cluster reset"	| redis-cli -p $PORT
    done
    ./redis-trib.rb create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002
}

case "$1" in
    start)
        start
        ;;
	stop)
        stop
        ;;
    init)
        init
        ;;
    *)
        echo "wrong args"
esac
